<?php
/**
 * Copyright 2014 Adobe
 * All Rights Reserved.
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/**
 * @var Link $block
 * @var Escaper $escaper
 */
?>
<?php if ($block->isPossibleOnepageCheckout()): ?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= $escaper->escapeHtmlAttr(__(' Checkout')) ?>"
            data-mage-init='{
                "Magento_Checkout/js/proceed-to-checkout":{
                    "checkoutUrl":"<?= $escaper->escapeJs($block->getCheckoutUrl()) ?>"
                }
            }'
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()): ?>
                disabled="disabled"
            <?php endif; ?>>
               <span class="checkout-icon" aria-hidden="true">
            <svg width="20"
                 height="20"
                 viewBox="0 0 24 24"
                 fill="none"
                 xmlns="http://www.w3.org/2000/svg">

                <path d="M12 3L19 6V11C19 15.5 16.1 19.4 12 21C7.9 19.4 5 15.5 5 11V6L12 3Z"
                      stroke="currentColor"
                      stroke-width="1.6"
                      stroke-linejoin="round"/>

                <path d="M9 12L11 14L15 10"
                      stroke="currentColor"
                      stroke-width="1.6"
                      stroke-linecap="round"
                      stroke-linejoin="round"/>

            </svg>
        </span>
        <span><?= $escaper->escapeHtml(__(' Checkout')) ?></span>
    </button>
<?php endif?>
